# Generated by Django 5.0 on 2023-12-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persent', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('last_payed', models.DateField()),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sum_payed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_differential', models.BooleanField(default=True, editable=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
        ),
    ]
