# Generated by Django 5.0 on 2023-12-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='is_differential',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='last_payed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='persent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
