# Generated by Django 5.0 on 2023-12-10 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_credit_is_differential_alter_credit_last_payed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='period',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='last_payed',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
