# Generated by Django 5.0 on 2023-12-08 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saving_account',
            field=models.OneToOneField(default=uuid.uuid4, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='saving_account', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='accounts.account'),
        ),
    ]
