# Generated by Django 5.0 on 2023-12-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_saving_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_key',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
