# Generated by Django 5.0 on 2023-12-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_key',
            field=models.IntegerField(null=True),
        ),
    ]
