# Generated by Django 5.0 on 2023-12-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0006_alter_user_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saving_account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='saving_account', to='accounts.account'),
        ),
    ]
